### ISSUE TITLE
Extracting all data from all the private repo when personal token is provided

### ISSUE THREAD

**Issue by rajatvijay** [codersrank-org/repo_info_extractor#111]
Now:
Extract data one-by-one for every private repo

Feature Request:
Extract data from all private repos in a single go

**Comment by brunolm** [comment]
@rajatvijay I've implemented this analyzer in Node.js and I included this feature https://github.com/brunolm/codersrank-analyzer

The plan is to have `npx @brunolm/codersrank-analyzer` work in the future so you don't have to clone the project or do anything else

**Comment by peti2001** [comment]
@rajatvijay, how do you imagine it?
1. Providing a list of repositories in the CLI. E.g.: `./run-docker.sh /path/to/repo1 /path/to/repo2 /path/to/repo3`
2. Provide a path and recursively find all the git repos in it? E.g. `./run-docker.sh /path/to/repos`

**Comment by peti2001** [comment]
@brunolm, I can see in your script the GitHub private key must be set. Why not setting it in Codersrank and your code will be checked weekly automatically?
<img width="325" alt="Screen Shot 2020-06-30 at 9 07 10 PM" src="https://user-images.githubusercontent.com/2922738/86166857-c7433800-bb15-11ea-87a9-f5a2932cf922.png">

**Comment by brunolm** [comment]
@peti2001 the concern is with security. Companies or individuals might not want people to do this as it could expose client project information.

There's no page saying what you do with the code (that I know of) and nothing that "guarantees" that it's safe.

Not that I don't trust you guy, but companies might be scared of having employees do this. Your PO said that you follow the best practices, delete projects after analyzing it etc, but there is still an uneasy felling for the company.

**Comment by peti2001** [comment]
Ok, I got it.
We want to keep the `repo_info_extractor` simple. The purpose of this script is to extract data from the local copy. However, I can image a wrapper what gets the private token checks out all the repos and uses the `repo_info_extractor` to extract the data.

What do you think about a solution like this?

**Comment by brunolm** [comment]
I'd be happy with whatever is easy to use, can extract all the user repos at once and doesn't have anything interactive (currently you have to answer what your email is and if you want to upload automatically)

I guess my "fork" already does what I wanted from this issue.

**Comment by peti2001** [comment]
Just to better understand your use case. How many repos you do want to extract and how often do you extract them?

**Comment by brunolm** [comment]
Me personally I think 10+, for some co-workers it could be Idk, maybe 50+
maybe every 6 months

My company was rank 1 but we dropped. We wanted an easy and safe way to have everyone in the company create a profile there so we could move back up.

**Comment by peti2001** [comment]
We really appreciate the work you have done with your custom `repo_info_extractor`. If there is a need for it I think it is important to add official support for this feature.

One possible solution:
We will create a wrapper Python script that uses the `repo_info_extractor`. The wrapper will have the token and emails as parameters (like @brunolm's solution), that will check out the repos and run the `repo_info_extractor`. 

We can do the same with a Bash script but it won't work on Windows.

How do you like this proposal?

**Comment by brunolm** [comment]
Sounds good to me.

And I think @rajatvijay, the person who started this issue (completely unrelated to me), would be fine with it too, I guess :P

**Comment by peti2001** [comment]
There are 28 👍 on this ticket so I guess other people are concerned as well. I am interested in everyone's opinion :).

**Comment by sulaysumaria** [comment]
For me, I have my repositories distributed across Bitbucket, Github and Gitlab. The solution discussed here is around Github only I think.

What I (and many other) would like is to have a script that can scan through my "projects" folder and extract info from all the repositories and upload to Codersrank. Because even though they are hosted on different platforms, I have all of them already checked out on my local machine.

I think this can be useful to a lot of people who might use some other private git tool.

**Comment by brunolm** [comment]
This is exactly what could never have happened

![image](https://user-images.githubusercontent.com/706078/87252216-a0ef9780-c447-11ea-8209-157bfa252c9f.png)

What `some user data has been compromised` means specifically? How screwed are we?

**Comment by peti2001** [comment]
Finally, we come up with a solution: https://github.com/codersrank-org/multi_repo_extractor.

**Comment by eriktelepovsky** [comment]
> https://github.com/codersrank-org/multi_repo_extractor

**This repository has been archived by the owner. It is now read-only.**

Not working anymore?

When I run multi_repo_extractor_osx, I get following error:

```
Checking for new versions
Couldn't find the latest version, skipping update. Error: Couldn't parse current version
2021/05/20 15:13:38 unexpected end of JSON input
```

**Comment by peti2001** [comment]
It is not maintained anymore. We are working to add those features to the `repo_info_extractor`. Check the updates because it will be in the next release.
