### ISSUE TITLE
404s on token page

### ISSUE THREAD

**Issue by Berkmann18** [codersrank-org/repo_info_extractor#116]
When I click <kbd>ENTER</kbd> when the `Do you want to upload the result to your profile automatically? [Y/n]` prompt shows up, it opens a new tab on my browser which **always** (I've reproduced that on all private repos I where I used this script) shows this:
![image](https://user-images.githubusercontent.com/8260834/85792739-e748b500-b72b-11ea-8341-a5f86146f819.png)

**Comment by peti2001** [comment]
Thanks. We are looking into to.

**Comment by peti2001** [comment]
It is supposed to be fixed. Can you please have a look at it?
@Berkmann18

**Comment by Berkmann18** [comment]
@peti2001 It seems to work now!
