### ISSUE TITLE
stderr: 'fatal: not a git repository (or any parent up to mount point /)

### ISSUE THREAD

**Issue by AlexWayfer** [codersrank-org/repo_info_extractor#117]
```
> ./run.sh ~/Projects/private_project/
Search repos on /home/alex/Projects/private_project/, 1 folders deep 
Found 1 repos under /home/alex/Projects/Work/private_project/
 
Analyzing repo under /home/alex/Projects/private_project ...
[============================================================] 100.0% ...Analyzing commits
? The following contributors were found in the repository.             Select which ones you are. (With SPACE you can select more tha
[22/07/2020 02:33:00] Filtering commits by emails:  ['popov@key-g.com', 'alex.wayfer@gmail.com']
[22/07/2020 02:33:00] Copying the repository to a temporary location, this can take a while...
[22/07/2020 02:35:27] Finished copying the repository to /tmp/396f02a3-89df-4273-bed4-3ea513cfb81b
Traceback (most recent call last):
  File "src/main.py", line 58, in <module>
    main()
  File "src/main.py", line 46, in main
    initialize(args.directory, args.skip_obfuscation, args.output,
  File "/home/alex/Projects/repo_info_extractor/src/init.py", line 93, in initialize
    libs = al.get_libraries()
  File "/home/alex/Projects/repo_info_extractor/src/analyze_libraries.py", line 47, in get_libraries
    repo = self._initialize_repository(tmp_repo_path)
  File "/home/alex/Projects/repo_info_extractor/src/analyze_libraries.py", line 177, in _initialize_repository
    repo.git.clean('-fd')
  File "/home/alex/.local/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/alex/.local/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/alex/.local/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clean -fd
  stderr: 'fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'
Finished

> ls /home/alex/Projects/private_project
branches/       config       FETCH_HEAD  hooks/  info/  objects/   packed-refs
COMMIT_EDITMSG  description  HEAD        index   logs/  ORIG_HEAD  refs/
```

**Comment by AlexWayfer** [comment]
The second run (without touching destination dir) was successful.

**Comment by peti2001** [comment]
Closing it.

**Comment by AlexWayfer** [comment]
> Closing it.

Why?

**Comment by peti2001** [comment]
After selecting the email address the script goes through all the commits. But before it to avoid messing up your local copy it makes a copy into a temporary directory. `/tmp/396f02a3-89df-4273-bed4-3ea513cfb81b` in your case.
Most probably something happened during the copy. 

How come the Git files are in the `/home/alex/Projects/private_project` directory and not in `/home/alex/Projects/private_project/.git`?

**Comment by AlexWayfer** [comment]
> Most probably something happened during the copy.

I think, we should fix this "something".



> How come the Git files are in the `/home/alex/Projects/private_project` directory and not in `/home/alex/Projects/private_project/.git`?

Sorry, I didn't understand the question.

**Comment by peti2001** [comment]
That something most probably client issue. There can be many reasons, not enough free space, something cleaned up the temporary folder, etc. 
If you can provide more details, how to reproduce it we can start investigating it. Is it still happening btw?

When you list the content of the `/home/alex/Projects/private_project` I would expect the files from your private repos, but it shows files which are usually in the `.git` the folder and this is weird.

**Comment by AlexWayfer** [comment]
> If you can provide more details, how to reproduce it we can start investigating it. Is it still happening btw?

Yes. You can add some debug actions in a separate branch and I can run it.




> When you list the content of the `/home/alex/Projects/private_project` I would expect the files from your private repos, but it shows files which are usually in the `.git` the folder and this is weird.

I see `.git/` directory in the new `tmp` one:

```
> ls -lah /tmp/ce267582-2dda-42d6-bd8a-0d92140fd7af/.git
total 0
drwxr-xr-x   8 alex alex  320 Jun 14 23:17 ./
drwxr-xr-x  23 alex alex 1.2K Jun 14 23:17 ../
drwxr-xr-x   2 alex alex   40 Aug 20  2017 branches/
-rw-r--r--   1 alex alex    0 Aug 30 16:06 COMMIT_EDITMSG
-rw-r--r--   1 alex alex    0 Aug 30 16:06 config
-rw-r--r--   1 alex alex    0 Aug 30 16:06 description
-rw-r--r--   1 alex alex    0 Aug 30 16:06 FETCH_HEAD
-rw-r--r--   1 alex alex    0 Aug 30 16:06 HEAD
drwxr-xr-x   2 alex alex  240 Aug 20  2017 hooks/
-rw-r--r--   1 alex alex    0 Aug 30 16:06 index
drwxr-xr-x   2 alex alex   80 Mar 10 22:17 info/
drwxr-xr-x   3 alex alex   80 Mar 10 22:17 logs/
drwxr-xr-x 260 alex alex 5.1K Mar 10 22:17 objects/
-rw-r--r--   1 alex alex    0 Aug 30 16:06 ORIG_HEAD
-rw-r--r--   1 alex alex    0 Aug 30 16:06 packed-refs
drwxr-xr-x   5 alex alex  120 Mar 11 08:42 refs/
```

> That something most probably client issue.

What do you mean about "client"? User, PC environment, this program?

> There can be many reasons, not enough free space, something cleaned up the temporary folder, etc.

Oh, shi… now I see error in any new terminal tab:

```
cat: write error: No space left on device
/usr/lib/rbenv/libexec/rbenv-init: line 110: cannot create temp file for here-document: No space left on device
cat: write error: No space left on device
/home/alex/.nodenv/libexec/nodenv-init: line 110: cannot create temp file for here-document: No space left on device
Welcome to fish, the friendly interactive shell
```

And yes, my RAM is still filled up even after extractor exception. 32 GB! I'm sure this issue should be resolved!

**Comment by peti2001** [comment]
Wow, that must be a huge repo. What is the output of this `du -sh .git/`?
