### ISSUE TITLE
Different email and limit processing commits upto certain date

### ISSUE THREAD

**Issue by yasirmturk** [codersrank-org/repo_info_extractor#118]
How to provide multiple email for same user in different private repos and their commits for example yasir@companyA.com and yasir@companyB.com ??
Secondly, is it possible to limit processing to up-to one year back for example for huge repos??

**Comment by peti2001** [comment]
1. Now it is not possible to add multiple emails for different repos. You have to extract the repos one by one and select the emails addresses.

2. No, it is not possible. You can experiment with squashing the commits.

**Comment by matfax** [comment]
There is one email address that could safely be imported additional to the provided email address.
That is, `<username>@users.noreply.github.com`. This can be used at any time as a commit email when users don't want to share their real email address publicly in git.
It's mentioned in the GitHub documentation [here](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address).
GitHub automatically detects this address. However, I don't know if you have access to the GitHub username.

**Comment by peti2001** [comment]
> There is one email address that could safely be imported additional to the provided email address.
> That is, `<username>@users.noreply.github.com`. This can be used at any time as a commit email when users don't want to share their real email address publicly in git.

This script is used with any kind of Git repos (BitBucket, GitLab, etc), not just GitHub. So we cannot rely on the username. 
> GitHub automatically detects this address. However, I don't know if you have access to the GitHub username.

No, actually it is not available.

**Comment by yasirmturk** [comment]
@peti2001 any idea how to extract data from large repos then?? I mean this utility is pretty useless to real professionals then... many programmers work on huge repos with hundreds of users/emails and hundreds of thousands of commits... 
- therefore; it is critical to limit the scanning upto specific numbers of commits in history, otherwise this scripts runs forever even on high end mac machines

**Comment by peti2001** [comment]
@yasirmturk, We are planning to update the script to analyze only the given user's commits. Would that solve your case?

**Comment by yasirmturk** [comment]
I hope so

**Comment by peti2001** [comment]
@yasirmturk I think shallow clone might help you with the large repo problem. https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones

**Comment by peti2001** [comment]
we improved the `repo_info_extractor`'s performance significantly. I think it is not an issue anymore.
