### ISSUE TITLE
Support Perl module detection

### ISSUE THREAD

**Issue by ferki** [codersrank-org/repo_info_extractor#122]
Most of my open source activity are related to Perl, and most of it was quite obviously missing from the results on my profile. It turned out that the files with `.pm` extensions are not recognized as Perl modules, thus cannot be counted against Perl experience.

There are probably other Perl aspects missing, but this could be a first step towards a more complete experience. I plan to send an initial pull request to add support for this.

**Comment by peti2001** [comment]
Hi @ferki,

I am sorry, I have no experience in Perl. Does that mean we should parse the `.pm` files the same way as `.pl` files?

**Comment by peti2001** [comment]
I just saw your PR which answers my question :).

**Comment by peti2001** [comment]
It is merged and deployed, can you please confirm it works with your repos?

**Comment by ferki** [comment]
> It is merged and deployed, can you please confirm it works with your repos?

Great, thanks! I did get some extra score for Perl now, so hopefully others will get a boost too :+1: 

ps.: I noticed a strange thing though. I get score for the forks of a repo as well, often more than I get for the canonical one. Not sure if that's normal or expected (or even related).

**Comment by peti2001** [comment]
Thanks, I'll close this ticket. Tell me which repository is affected and I'll investigate it.
