### ISSUE TITLE
Upload the result automatically

### ISSUE THREAD

**Issue by peti2001** [codersrank-org/repo_info_extractor#13]
Improve the repo extractor (https://github.com/codersrank-org/repo_info_extractor) to give the user an option to upload the result automatically. This option should be available after selecting the email address.

**Comment by seigieu** [comment]
But please, leave it as option... I want to control what I upload :)

**Comment by peti2001** [comment]
Exactly. Until you allow to upload the file there is not network traffic between the script and the servers.
As we planed it will work like this:
1. After you selected the email address you will see this question:
> Do you want to upload the file automatically? (y/n)
If you select no that the script will work as before
2. If you select yes, then the file will be uploaded to temporary storage. 
3. A link with a unique token will be shown. You have to follow the link in order to validate your codersrank account.
4. If you follow the link you will be redirected to this page:
<img width="1667" alt="Screen Shot 2019-07-18 at 1 20 55 PM" src="https://user-images.githubusercontent.com/2922738/61459538-407d6580-a96d-11e9-986a-0dcf88060aa1.png">
Where you can see the progress of the upload
