### ISSUE TITLE
Add support for Robot Framework

### ISSUE THREAD

**Issue by peti2001** [codersrank-org/repo_info_extractor#137]
Robot Framework is a generic open source automation framework. It can be used for test automation and robotic process automation (RPA).
https://robotframework.org to technologies?
# Implementation
As I can see it is a Python framework and uses its own language to specify test cases, automation. So the easiest way to add support for it if we recognize `.rst` file extensions.

**Comment by fearless-spider** [comment]
Hi, 

the file extension for robot framework is .robot, there is also a keyword "Library" http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-test-libraries which is similar to "import" in python. Hmm, I will try to add RobotFramework to repo_info_extractor.

**Comment by peti2001** [comment]
Hi,

Thanks. I think it is quite convenient. Literally two lines of code. E.g. https://github.com/codersrank-org/repo_info_extractor/pull/121/files

**Comment by peti2001** [comment]
Support for `.robot` has been added.
