### ISSUE TITLE
gets stuck on Initialization...

### ISSUE THREAD

**Issue by aryehbeitz** [codersrank-org/repo_info_extractor#15]
The tools runs well on just about all my private repositories.

I have one which is over four years old and the tool gets stuck at the text `Initialization...`.
It's been over an hour.
What can I do?

I can't give access to the repository as it's private. Is there a way to debug this? Maybe a parameter which displays the commands being run so I can see on which it is getting stuck?

Much thanks!

**Comment by peti2001** [comment]
Hi,
During the initialization, it goes through all the commits and it might take some time. We tested it with some quite big repo (+50K commits). How many commits do you have in that repo?

**Comment by peti2001** [comment]
Hi, any update here?
