### ISSUE TITLE
fatal: cannot chdir to 'path': No such file or directory

### ISSUE THREAD

**Issue by ErickPetru** [codersrank-org/repo_info_extractor#153]
I already was able to extract a private repository successfully using `run-docker.ps1` with PowerShell on Windows 10 + Docker 19. Then, when I gone to try with another one, an error was throwed just in the beginning of the analysis:

![image](https://user-images.githubusercontent.com/242274/99112189-0dcc9700-25cc-11eb-87ec-1d5bca1399fe.png)

I'm confident this folder is the right one, with a valid Git repo there:

![image](https://user-images.githubusercontent.com/242274/99112360-4bc9bb00-25cc-11eb-900d-0ec536ff162b.png)

Also, it have the same tech stack (Vue + Nuxt) as the other repository which worked successfully.

**Comment by peti2001** [comment]
We released a new version of the `repo_info_extractor`. This is not relevant anymore.
