### ISSUE TITLE
Passing extra parameters to docker container (email, output filename, etc)

### ISSUE THREAD

**Issue by andrey-helldar** [codersrank-org/repo_info_extractor#159]
Currently, passing additional parameters to the docker container is ignored.
Tell me how can I specify the search for commits by email, as well as how to specify the name of the saved file?

My case:

```batch
// repositories.bat

foo/bar
foo/baz
```

```batch
// codersrank.bat

@echo off

setlocal ENABLEDELAYEDEXPANSION

set email="<my@email>"

cd ./codersrank

for /F "tokens=*" %%A in (../repositories.txt) do (
	set repository=%%A
	call set filename=!repository:/=-!

	call git -C c:/dev/domains/%%A pull
	call run-docker.bat c:/dev/domains/%%A --email=%email% --output=!filename!.json
)
```

The `--email`, `--output` and `--skip_upload` options are currently ignored.

![image](https://user-images.githubusercontent.com/10347617/106441314-f2ff1580-648a-11eb-9788-85fecc552dfa.png)

**Comment by peti2001** [comment]
Hi @andrey-helldar,
Currently, we are not adding new features because we are planning a refactoring. Check out our plans and share your thoughts #160.

**Comment by andrey-helldar** [comment]
Hi!
Understood thanks! I'll think about what I'm missing and write 🙂
