### ISSUE TITLE
Mac installation & usage

### ISSUE THREAD

**Issue by bfintal** [codersrank-org/repo_info_extractor#16]
Got this working on a Mac with:

```bash
$ git clone https://github.com/codersrankOrg/repo_info_extractor.git
$ cd repo_info_extractor
```

Install `pip` (from https://stackoverflow.com/a/38043109/174172) & other requirements:

```bash
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python get-pip.py
$ sudo pip install -r requirements.txt
```

```bash
$ sudo ./install.sh
$ ./run.sh path/to/repository
$ ls -al ./repo_data.json
```

**Comment by peti2001** [comment]
Update README with OSX instructions.

**Comment by peti2001** [comment]
Thanks for the suggestion. I updated the README, can you have a look at it?

**Comment by texpert** [comment]
I would suggest to add some notes or even make optional the installation in userspace (thus, avoiding the `sudo`):

`$ python get-pip.py --user`

and in the install.sh:

`pip install -r requirements.txt --user`

**Comment by peti2001** [comment]
Thanks for your recommendation. I decided we won't explain Python and pip installation processes.
See my explanation here: #24
