### ISSUE TITLE
panic: exit status 1

### ISSUE THREAD

**Issue by DieterHolvoet** [codersrank-org/repo_info_extractor#168]
I'm trying out v0.9.2 and with 6 out of 75 projects, I'm getting the following error:
```
panic: exit status 1

goroutine 1 [running]:
main.main()
	/Users/pkarakas/Work/codersrank/rie/main.go:50 +0x62d
```

**Comment by DieterHolvoet** [comment]
Found the issue: this happens when passing a folder with a Git repo that hasn't been initialized with its first commit.

**Comment by peti2001** [comment]
it is supposed to be fixed with the latest release. Can you please check it?

**Comment by DieterHolvoet** [comment]
Fixed!
Now I'm getting the following:
```
Initializing repository
Cannot get remote.origin.url. Use directory path to get repo name.
Analysing commits
Analysing libraries
Creating output file
Uploading result to CodersRank
Go to this link in the browser => xxx
```
