### ISSUE TITLE
Improve file upload

### ISSUE THREAD

**Issue by peti2001** [codersrank-org/repo_info_extractor#174]
At the end I got: "Uploading result to CodersRank" - but what if I don't want to immediately upload (old code had a -do_not_upload switch) - also to note a 🐛: the new file was not uploaded to codersrank, as the old file with the same name and old timestamp was kept there.

**Comment by hidegh** [comment]
- Ok, so the reason I did not wanted the file to upload is to manually give a meaningful name to the repo. But with #173 this will lose it's priority.
- Also some users might prefer to upload all files at once (they don't need to handle ev. upload issues by the tool)

❗ Note that I also reported a BUG: despite new repo-info being created and announced as uploaded, on the site I do still see just the old repo-info, but not the new one!
![image](https://user-images.githubusercontent.com/6331063/114316835-9d3b8f00-9b05-11eb-8d37-e1842604ad8e.png)

**Comment by peti2001** [comment]
I am planning to merge https://github.com/codersrank-org/multi_repo_extractor and https://github.com/codersrank-org/repo_info_extractor. Like that it would be possible to extract and upload multiple repos at once.

**Comment by hidegh** [comment]
@peti2001 I solved it with a powershell script :)

The reason this ticket is not closed:
- it's owned by you
- there's a BUG reported - no upload took place after extraction, despite the message written out

**Comment by sulaysumaria** [comment]
@peti2001 , is there a way to skip the uploads? I would like to upload all the zip files together from UI. It is tedious to say `n` to each repo. It will be better if we can add a flag to skip upload.

Here is the shell I use to extract for multiple repos:
```bash
find . -mindepth 1 -maxdepth 1 -type d -exec sh -c 'echo {} && ../repo_info_extractor_osx local --skip_update --repo_path {}' \;
```

**Comment by peti2001** [comment]
It is added. You can disable it with the `--skip_upload` global flag.

**Comment by sulaysumaria** [comment]
Hello @peti2001 , that works perfect thanks.

I would like to know if there is any way to upload all the zip files together to web? Currently I have to upload files one by one.

**Comment by peti2001** [comment]
Currently, it is not possible. However, we have the API endpoint, so it shouldn't be that difficult to add to the frontend.
