### ISSUE TITLE
BUGS: Project added via repo_extractor, evaluated, reloaded, yet no change in points nor is project mentioned under the given technology

### ISSUE THREAD

**Issue by hidegh** [codersrank-org/repo_info_extractor#175]
The graph visualizes the last 6 years.
I've added a project that run between 2013-2015/09 as a pivate repo (repo_extractor + upload).

NOTE:
- Tried an actual project, same situation, no points updated, etc.
- Also had to manually upload files

**Issues:**
1. don't see any change in points, nor in the graph, nor is the project mentioned in the C# detail list
![image](https://user-images.githubusercontent.com/6331063/114384355-e552c400-9b8e-11eb-9e9b-bb5cf1ae2983.png)

2. in the UI, when I list the repos I again don't see the total points for that repo
![image](https://user-images.githubusercontent.com/6331063/114384045-84c38700-9b8e-11eb-846f-089b6f3ac759.png)

3. The extractors does not cleans up the directory (a directory that has the same name as the output ZIP is remaining after extraction)

**Comment by hidegh** [comment]
@peti2001 meanwhile the issue with the points calculation was resolved, so ticket #178 and #177 can be closed. from this ticket the nr2  and 3 issues are still present.

**Comment by peti2001** [comment]
> 2. in the UI, when I list the repos I again don't see the total points for that repo
This is supposed to be fixed. Can you have a look at it? You might have to reupload the artifact.

**Comment by hidegh** [comment]
Status:
- 🐛 the manually uploaded repository list get's lost when I recalculate the exp. and reload the app
- 🆗 the total score for ALL repos is there
- 🚫 the score for a given repo is not there (see red mark in the picture)

![image](https://user-images.githubusercontent.com/6331063/115113913-f768a400-9f8c-11eb-8681-60f25069730f.png)

after adding, before exp. recalculation:
![image](https://user-images.githubusercontent.com/6331063/115114031-74941900-9f8d-11eb-90ec-edc599b69c38.png)

after exp recalc. + reload:
![image](https://user-images.githubusercontent.com/6331063/115114039-7b229080-9f8d-11eb-8d6e-904a7c695321.png)


W10, latest (actually before last/todays update) Chrome version.

**Comment by peti2001** [comment]
>  the manually uploaded repository list get's lost when I recalculate the exp. and reload the app

It is fixed. It was only a visualization issue. No profile refresh is required. Can you please have a look, and close the issue if it is really solved.

> the score for a given repo is not there (see red mark in the picture)

This has never been done. This is a feature request. Can you please create a new feature request?
