### ISSUE TITLE
gitlab repos added via access token recognised but scores not calculated

### ISSUE THREAD

**Issue by NicolasdRa** [codersrank-org/repo_info_extractor#177]
Gitlab repos added via access token are recognised but no experience points calculated, neither ar commits read since 23.03 even though daily commits are made.

Tried adding repo manuallly but remote.origin.url not read from config in repo

![image](https://user-images.githubusercontent.com/54933005/114679925-ed387280-9d0c-11eb-8030-c94f094cad57.png)

![image](https://user-images.githubusercontent.com/54933005/114679044-1b698280-9d0c-11eb-961f-bbf8cb2bc52c.png)

![image](https://user-images.githubusercontent.com/54933005/114679301-553a8900-9d0c-11eb-8e55-b93da81270a9.png)

**Comment by hidegh** [comment]
same #178 #175

**Comment by peti2001** [comment]
I recently deployed some changes that might solve this. There were some problems with the GitLab tokens. To solve it:
1. Revoke your GitLab access token in GitLab (https://gitlab.com/-/profile/applications)
2. Refresh your profile
3. You can add the GitLab integration again.

**Comment by NicolasdRa** [comment]
folllowed the indicated steps, added gitlab integration again and same result, repos added, 0 exp points recognised. All gitlab activities removed from history.

![image](https://user-images.githubusercontent.com/54933005/115087864-57206a00-9f0f-11eb-96c1-c871b44b73f3.png)

**Comment by peti2001** [comment]
@NicolasdRa this is something different. According to the logs we couldn't clone the repo. This is the error: `The project you were looking for could not be found.`. Is the URL of the GitLab repos like this
`https://gitlab.com/vendor/repo_name.git/`

**Comment by NicolasdRa** [comment]
@peti2001 this is the kind of url: 

url = git@gitlab.com:xxx-xxxxxxx/frontend/ui-account-management.git

when trying to use the extractor (strategy which I also tried ), I get "cannot get remote.origin.url" error

**Comment by hidegh** [comment]
@NicolasdRa This is the same issue I had. You need to supply a git_path via parameter.

Need to use RECENT releases or repository and you should get a better error, which makes you immediately notice that it's the access to GIT.EXE the real problem.

**Comment by peti2001** [comment]
@NicolasdRa, can you check your profile now?
We deployed a fix to handle repos with the URL format you mentioned.

**Comment by NicolasdRa** [comment]
@peti2001 
 Profile checked, repos recognised and computed,  issue solved, thanks!

**Comment by NicolasdRa** [comment]
> @NicolasdRa This is the same issue I had with the extractor. You need to supply a git_path (check the docs for the proper name) via parameter. Or see: [#173 (comment)](https://github.com/codersrank-org/repo_info_extractor/issues/173#issuecomment-821157579)
> 
> Need to use RECENT releases or repository and you should get a better error, which makes you immediately notice that it's the access to GIT.EXE the real problem.
> 
> Also previously after uploading the extracted repo, there were no exp. points added, but that resolved in the last days.
> 
> Now the added repo-list is vanishing (but at least points stay).

git path was not the issue in this case, after last patch issue was solved.
