### ISSUE TITLE
Manually added and evaluated repositories are not contributing towards overall score

### ISSUE THREAD

**Issue by pritam001** [codersrank-org/repo_info_extractor#178]
https://profile.codersrank.io/user/pritam001

I've added 56 manual repos but it still says "You haven't got any experience from private repositories, yet. Please upload at least one!"

**Comment by hidegh** [comment]
same #177 #175

**Comment by pritam001** [comment]
Issue is resolved. Thanks @peti2001 for quick response.

**Comment by peti2001** [comment]
Great!
