### ISSUE TITLE
BUG: badges missing from the UI app and from UI admin interface

### ISSUE THREAD

**Issue by hidegh** [codersrank-org/repo_info_extractor#179]
after exp. recalculation I'm almost on the same level, so TOP: 13, 44, 47 in some ranks,
yet there's no badges shown.

previously top 1/5/50/100 badges were avail to select from the "badge admin" menu, now that's empty.

**Comment by hidegh** [comment]
@peti2001 anyone who could look into this? why aren't any badges showing up?

Also maybe a FR: make all badges visible, so user sees what are the requirements for that and do allow just to pick those, which were earned!

**Comment by peti2001** [comment]
Hi @hidegh,

You cannot have badges unless you provide a location. Set at least the country.

**Comment by hidegh** [comment]
Quick notes for others having the same issue: **after setting location, you need to re-calculate the points and reload**

@peti2001 there's also a world-wide score, maybe such badges would be cool too :)
