### ISSUE TITLE
Syntax mixing

### ISSUE THREAD

**Issue by MarvinKweyu** [codersrank-org/repo_info_extractor#18]
I may be wrong but,why are you mixing syntax between python 2 and 3 in **upload.py**?
The function `showError()`,on one part we have `print err` while on another `print("Unable ...")`.
So I change to python 3 syntax to find `raw__input().lower()` in **questions.py**. Am I missing something?

**Comment by peti2001** [comment]
Thanks for highlighting it. Now it is supposed to be fixed in Python2/3. Can you please check it?

**Comment by MarvinKweyu** [comment]
It works. A plus on proper indentation to `upload.py`. Forked the repo to help out where I can.
