### ISSUE TITLE
Keeping downloading "new version" even if it is already the new one

### ISSUE THREAD

**Issue by nunomazer** [codersrank-org/repo_info_extractor#184]
Everytime I run repo_info_extractor_linux it downloads new version, even it is the new one.

I run `ls` and can see the _old file, run it and download occurs, never leting me to download the repos

**Comment by livike** [comment]
It's the same for the windows version too.

**Comment by peti2001** [comment]
I set the wrong version in the latest release. That is why it kept downloading. After you download the latest version it is supposed to be fixed. Can you confirm?
