### ISSUE TITLE
Error executing the "python src\main.py path\to\repo" command on windows

### ISSUE THREAD

**Issue by cedaniel200** [codersrank-org/repo_info_extractor#19]
Hi

When executing the "python src\main.py path\to\my_repo" command on windows

I get the following result:

Traceback (most recent call last):
  File "src\main.py", line 4, in <module>
    from export_result import ExportResult
  File "D:\projects\Coders Rank\repo_info_extractor\src\export_result.py", line 5, in <module>
    from upload import uploadRepo
  File "D:\projects\Coders Rank\repo_info_extractor\src\upload.py", line 11
    r = requests.post(url, files=files)
                                      ^
TabError: inconsistent use of tabs and spaces in indentation

somebody can help me. Thanks
----------------------------------------
Windows 10
Python 3.7.4

**Comment by gurupratap-matharu** [comment]
Hi I am facing the same issue.

Could you give an example of url of the private repo.
I tried various combinations but get the same error on windows10

**Comment by cedaniel200** [comment]
I tried both with absolute and relative route and none worked for me. For example

C:\folder\folder\my_repo
..\..\my_repo

**Comment by peti2001** [comment]
Hey guys,
I just pushed some changes. Can you update your code and check it again?

**Comment by cedaniel200** [comment]
Thanks, with the changes, everything works fine
