### ISSUE TITLE
multi_repo_extractor

### ISSUE THREAD

**Issue by eriktelepovsky** [codersrank-org/repo_info_extractor#190]
Hello.

https://github.com/codersrank-org/multi_repo_extractor git repository is DEPRECATED and merged into repo_info_extractor.

So how to use multi_repo_extractor?

**Comment by peti2001** [comment]
Hi @eriktelepovsky,

That project is archived. Check out the latest release candidate that has some functionality of the multi_repo_extractor.
https://github.com/codersrank-org/repo_info_extractor/releases
