### ISSUE TITLE
Error: unknown flag: --repo_path

### ISSUE THREAD

**Issue by WaAlvis** [codersrank-org/repo_info_extractor#194]
I am trying to enter my repository with the **./repo_info_extractor_osx --repo_path ./path_to_repo** command, but I always get the same message, I already restart my mac, but it still does not work, does anyone know the reason?

![image](https://user-images.githubusercontent.com/41210700/127864620-30570507-d096-44c0-bea9-8c3fdfacb4e0.png)

**Comment by letehaha** [comment]
Hey @WaAlvis, you need to add `local` to the command:

```sh
./repo_info_extractor_osx local --repo_path ./path/to/repo
```
[There](https://github.com/codersrank-org/repo_info_extractor#available-commands) it is described a bit  🙂 

@peti2001 looks like this command in [that](https://github.com/codersrank-org/repo_info_extractor#binary-approach-easiest) README section should be updated 🙂

**Comment by WaAlvis** [comment]
Thank you very much @letehaha , I got caught up in this part, but with your intervention I managed to update my profile in codeRank.

**Comment by peti2001** [comment]
> Hey @WaAlvis, you need to add `local` to the command:
> 
> ```shell
> ./repo_info_extractor_osx local --repo_path ./path/to/repo
> ```
> 
> [There](https://github.com/codersrank-org/repo_info_extractor#available-commands) it is described a bit 🙂
> 
> @peti2001 looks like this command in [that](https://github.com/codersrank-org/repo_info_extractor#binary-approach-easiest) README section should be updated (`local` is missing) 🙂

Indeed it was outdated. I updated it.

Thanks @letehaha
