### ISSUE TITLE
Issues uploading a private repo

### ISSUE THREAD

**Issue by bluemorgan23** [codersrank-org/repo_info_extractor#198]
![1600_129_1](https://user-images.githubusercontent.com/47163411/131589076-4c9ecd35-d1b1-45c9-99fd-65085f846dc4.png)

I also noticed that several unit tests are failing. I can post screenshots of these errors if needed.

**Comment by peti2001** [comment]
Hi @bluemorgan23,

I have no problem running the tests. All of them pass. 
<img width="828" alt="Screen Shot 2021-09-07 at 1 14 52 PM" src="https://user-images.githubusercontent.com/2922738/132335770-5465364c-3e50-484a-826e-eba204a629a8.png">

Can you give me more details about the connection error? How often does it happen?
