### ISSUE TITLE
Recognize Gentoo ebuild and eclass files

### ISSUE THREAD

**Issue by ferki** [codersrank-org/repo_info_extractor#207]
As a Gentoo package maintainer, I would like repo_info_extractor to recognize my related code, so my real experience may get better represented on codersrank.

Gentoo's default package manager is portage, which works with ebuild files. According to their devmanual's [Ebuild File Format](https://devmanual.gentoo.org/ebuild-writing/file-format/index.html) page:

> An ebuild is a `bash` script which is executed within a special environment. Files should be simple text files with a `.ebuild` extension.

I believe this would be relatively simple to detect.

As far as the categorization is concerned, `Shell` is already recognized, so that could be a candidate among the existing ones. Since ebuilds are a special case of shell scripting, it might worth to introduce it on its own as a category, though. Perhaps even `Packaging` or similar could work even better in order to support further similar formats, like Void Linux [templates](https://github.com/void-linux/void-packages/blob/c0ed7caebeb4c4984d8d2b7b35b197b6e5ee9a81/srcpkgs/hitch/template), or Arch Linux [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/d46ee78a8f6634bc894608f23fd0be1372a79314/trunk/PKGBUILD) files, etc.

I see this project has changed considerably since my last direct experience with it, but I might be able to contribute initial support if this idea is considered for inclusion.

What do you think?

UPDATE: it would be nice to include [eclass files] as well under the same rules, which could be treated the same when detecting the `.eclass` extension.

**Comment by ferki** [comment]
Based on [my overlay](https://github.com/ferki/gentoo-overlay)'s language info, it looks like GitHub recognizes ebuilds as `Shell`.

According to a [comment](https://github.com/github/linguist/issues/1655#issuecomment-61393535) on github/linguist#1655:

> It says Shell because the .ebuild files are under the parent language Shell.
Thus, the statistics display Shell but the files are really detected (and highlighted) as Gentoo Ebuild.

Next to the relevant [code part for ebuild](https://github.com/github/linguist/blob/7e7100cc4f1ac9f9cd55bc8c788ce140886ced3c/lib/linguist/languages.yml#L1974-L1984), there is also [code for eclasses](https://github.com/github/linguist/blob/7e7100cc4f1ac9f9cd55bc8c788ce140886ced3c/lib/linguist/languages.yml#L1985-L1995), which would also be nice to add.

**Comment by peti2001** [comment]
I have implemented the changes. Tomorrow I'll try them. In your previous commits, I could find an `.ebuild` but I couldn't find an `.eclass`. Can you send an example?

**Comment by ferki** [comment]
Thank you, @peti2001! I don't have an eclass in my overlay at the moment, but I can point to [upstream's collection](https://github.com/gentoo/gentoo/tree/master/eclass) for examples. Eclasses are like "libraries" to be included in ebuilds to share common functionality; we might be even able to recognize them later as such.

Please note that these files are licensed under GPLv2, so including them as test examples here in an MIT licensed project might get complicated (I am not a lawyer, though). Solely recognizing the extensions should be fine, I believe :+1: 

I also found your commit on the `recognize_ebuild_eclass_files` branch, and now I see I could have just sent a patch easily, thanks. I remembered it to be more involved, but my last contribution here was before the rewrite :slightly_smiling_face:

I don't feel convinced if ebuilds and eclasses should have their own new categories, though :thinking: If I approach this question from the perspective of "how I would prefer to have them represented as coding experience?", I have the following thoughts:

- They are shell (Bash) files, so I would be fine to have my experience with them counted as `Shell` experience (and that would match e.g. how GitHub represents them too).
- A more inclusive/extensible approach might be to include them in a new `Package` or `Packaging` category instead of `Shell`. I would be happy to be more explicit, and show that I am packaging software (but I might do it for other distros too, not just Gentoo, hence the umbrella term).
- It might be also fine to represent it as `Ebuild packaging` or `Gentoo packaging` to be even more specific, but I am not sure how well that naming scheme would fit the site, or scale later (e.g. having a new category for every OS packaging format).

**Comment by peti2001** [comment]
Thanks, @ferki!

I would vote for putting them into the `Eclass` and `Ebuild`. For the following reasons:

- Until your comment, I haven't known `Packaging` is a thing and I am afraid many other people looking at a profile won't have any idea what is that. If we mask the language they won't even have a chance to Google it. 
- We don't have the concept of categories. It feels like putting `Kotlin` and `Swift` under the `Mobile` category. What we don't do. 
- Even though they are bash files I would not put them under the `Shell` language. We lose a piece of important information about the packaging. 
- I don't mind showing `Ebuild` on a profile. Most probably 95% of the developers won't know what is that but after a quick search, they will learn and it will be clear what you actually do with that language. 

How do you see?

**Comment by ferki** [comment]
> * Until your comment, I haven't known `Packaging` is a thing and I am afraid many other people looking at a profile won't have any idea what is that. If we mask the language they won't even have a chance to Google it.

IMHO software packaging is a relevant experience on the IT job market, and folks working around software delivery responsibilities ((Dev)Ops, build automation, and release engineers, etc.) would like to highlight on their technical profile in some form.

And yeah, the term to Google would definitely be `ebuild` :+1: 

> * We don't have the concept of categories. It feels like putting `Kotlin` and `Swift` under the `Mobile` category. What we don't do.

Yeah, looks like I haven't remembered the levels of organization correctly, and was thinking about broader competencies instead of focusing on languages (and their popular frameworks/libraries).

> * Even though they are bash files I would not put them under the `Shell` language. We lose a piece of important information about the packaging.

I still think `Shell` would be an acceptable option, since it highlights the experience of working with complex shell systems and concepts. If we can afford to be more specific than that, let's go for that, though! :)

> * I don't mind showing `Ebuild` on a profile. Most probably 95% of the developers won't know what is that but after a quick search, they will learn and it will be clear what you actually do with that language.

While the actual language is still Bash, I agree using `Ebuild` could help to make it distinct from general shell scripting.

> How do you see?

By now, I only wonder about whether `eclass` should be a separate "language" or not :thinking: Eclasses are reusable code written in Bash to be imported/included into ebuilds. For example writing

```bash
inherit autotools
```

in an ebuild would import the `autotools` eclass, and e.g. a function defined in the eclass would be usable in the ebuild.

In that sense, an eclass might be more of a library in CodersRank context. So perhaps let's just count them as `Ebuild` too, for now?

**Comment by peti2001** [comment]
I like your suggestion to merge `eclass` and `ebuild` to the same language. I have released these changes. If you refresh your profile you will see the new language.

**Comment by ferki** [comment]
Great, thank you! :tada:
