### ISSUE TITLE
Windows release version 2.3.2 does not work

### ISSUE THREAD

**Issue by kitswas** [codersrank-org/repo_info_extractor#213]
Binary downloaded from https://github.com/codersrank-org/repo_info_extractor/releases/tag/v2.3.2

Windows gives me the error

```
This version of xxxx\repo_info_extractor_windows.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

Older versions work on my machine.

**Comment by peti2001** [comment]
Thanks for reporting the issue, we are looking into it.

**Comment by peti2001** [comment]
Meanwhile, you can use an older version: https://github.com/codersrank-org/repo_info_extractor/releases and turn off the auto-update with the `--skip_update` option.

**Comment by peti2001** [comment]
@kitswas, it is supposed to be fixed. Tested on an AMD laptop with Win 11. The problem was I build an ARM version of the binary accidentaly.
