### ISSUE TITLE
Top percent calculation issue in Technologies

### ISSUE THREAD

**Issue by formidablae** [codersrank-org/repo_info_extractor#216]
Don't know where to open this issue...

There is a problem in the calculation of the Top <x>% in the Technologies section in https://profile.codersrank.io/user/<username>.

Basically with a score of 399.4 out of 26576 users => Top 1%.

![image](https://user-images.githubusercontent.com/81068781/204090167-023d0943-e184-4e10-b2dd-a2511f531746.png)

The same user with a score of 423.7 out of 26576 users => Top 9%.

![image](https://user-images.githubusercontent.com/81068781/204090322-42d187d7-20ea-4ece-9bf3-3fb84957ab35.png)

There might be something wrong there, maybe it was meant to be 0.9% (second case)...

**Comment by krogucci** [comment]
hi @formidablae I think you posted the wrong link - could you update it?

**Comment by krogucci** [comment]
I'm guessing this is the one: https://profile.codersrank.io/user/formidablae ?

**Comment by formidablae** [comment]
Yes, that's my profile link. I intended in general, in the tech section of every user's profile page.

**Comment by krogucci** [comment]
hi @formidablae we have fixed it now - the issue was not in the "Top 9%", but rather in the "Top 1%" which should have been "Top 10%" to begin with. Thanks a lot for reporting this one.
