### ISSUE TITLE
missing info in installation instructions for Linux

### ISSUE THREAD

**Issue by garak** [codersrank-org/repo_info_extractor#24]
I see that README suggests to install pip on OSX, but fails to do it on Linux (where is equally necessary).
You should add this line to Linux instructions:

`sudo apt install python-pip`

of course, alternate instructions should be provided for non-Debian based distros (something like "yum install python-pip", sorry I don't use RedHat-based distros)

**Comment by peti2001** [comment]
Python and pip installation are different in every platform. It shouldn't be our concern to explain every detail of it. There are much better well-written how-tos about it and we should help the users to find these.
So from now, there will be no Python and pip installation steps. Only external links, which we believe, are the most helpful.
