### ISSUE TITLE
No module named git

### ISSUE THREAD

**Issue by rodoufu** [codersrank-org/repo_info_extractor#3]
I've installed and I'm trying to run the run.sh and I'm getting the following error.

```
Traceback (most recent call last):
  File "src/main.py", line 2, in <module>
    import git
ImportError: No module named git
```
I've also installed gitpython

```
pip install gitpython
sudo apt-get install python3-git
```

I'm using Ubuntu 19.04 with python 3.7

**Comment by rolandopalermo** [comment]
I also have the same issue, I am running the script on Windows 10 and Python 3.6.4

**Comment by giansalex** [comment]
Try install requirements
```bash
pip install -r requirements.txt
```

**Comment by nicolasFernandez** [comment]
I've managed to solve it replacing python with python3 on run.sh

`python3 src/main.py "$@"`

**Comment by giansalex** [comment]
> I've managed to solve it replacing python with python3 on run.sh
> 
> `python3 src/main.py "$@"`

depends which python version used for install the requirements

**Comment by rolandopalermo** [comment]
In my case, the issue was due to I had two Python installations. I uninstalled one of them and the extractor worked fine

**Comment by giansalex** [comment]
> In my case, the issue was due to I had two Python installations. I uninstalled one of them and the extractor worked fine

@rolandopalermo,  I also have two python version, you need use same version for install the requirements and for run `main.py`

**Comment by rodoufu** [comment]
> I've managed to solve it replacing python with python3 on run.sh
> 
> `python3 src/main.py "$@"`

It worked for me.

**Comment by r787-ai** [comment]
You can try this.

GitPython’s git repo is available on GitHub, which can be browsed at:

https://github.com/gitpython-developers/GitPython and cloned using:

$ git clone https://github.com/gitpython-developers/GitPython git-python Initialize all submodules to obtain the required dependencies with:

$ cd git-python $ git submodule update --init --recursive
