### ISSUE TITLE
Add (fix) contributing documentation

### ISSUE THREAD

**Issue by AlexWayfer** [codersrank-org/repo_info_extractor#39]
I guess, you forgot something:

![image](https://user-images.githubusercontent.com/6510020/66691156-fb7f7b80-ec9c-11e9-9ee6-21f13a72abec.png)

**Comment by peti2001** [comment]
Thanks. Updated.

**Comment by AlexWayfer** [comment]
Thank you. Just a ref: resolved in 19e9737000cda1211a48fd864f34b5a875483123
