### ISSUE TITLE
Repository extraction does not work

### ISSUE THREAD

**Issue by jasp402** [codersrank-org/repo_info_extractor#4]
Follow each of the steps then place a route to a repository that is private but I have stored locally and started to process then started to appear this again and again.

![image](https://user-images.githubusercontent.com/8978470/60390976-71bef000-9aa9-11e9-8b2a-bc52d3bddaca.png)

**Comment by DaWe35** [comment]
Hey!
That's solved here: https://github.com/codersrank-org/repo_info_extractor/issues/2

**Comment by peti2001** [comment]
Supposed to be fixed on latest master. Can you confirm?

**Comment by peti2001** [comment]
Duplicated. See #2
