### ISSUE TITLE
Extract libraries from PHP

### ISSUE THREAD

**Issue by peti2001** [codersrank-org/repo_info_extractor#42]
# Introduction
We started to implement the `external library recognition` feature.
It means the `repo_info_extractor` will be able to recognize the used libraries and not just the programming language.

# How does it work?
Regexes are used to recognize library imports.
This library detection must be done language by language since each language has a different syntax to import libraries. 
We created a [`JavaScript` extractor](https://github.com/codersrank-org/repo_info_extractor/blob/master/src/language/JavaScript.py) as the first working library extractor. 

# Requirements
- Create a new extractor for PHP. Support PHP5 and PHP7 too.
- Place the new file here: https://github.com/codersrank-org/repo_info_extractor/tree/master/src/language
- Implement the `def extract_libraries(files):` function. The input this an array of paths to the files. The output is an array of the recognized libraries.
- Add UnitTest too here: https://github.com/codersrank-org/repo_info_extractor/tree/master/test

**Comment by amenadiel** [comment]
@peti2001 I'm not sure if it's a good idea to implement a parser for this. Given you can include whatever script you want and call a function from the global scope, we wouldn't be able to figure out what third party libraries is anyone actually using.

Even if there was a clean codestyle, the namespacing for a given library doesn't match the canonical name as provided in packagist/composer. Custom autoloaders (outside of version control and therefore invisible to **repo_info_extactor**) allow for aliasing a FQCN to anything.

I'd suggest sticking to the contents of  `composer.json` (explicit dependencies) or  `composer.lock` (including dependencies of dependencies), or a combination of both, like: nested dependencies but just one level deep.

The same approach would be sensible for other languages, at least as a transient solution in

- Python (pip -> requirements.txt)
- Ruby (rubygems)
- NodeJS (package.json, package-lock.json, yarn.lock)
- Frontend JS (bower.json, jspm.config.js, etc)

In due time you can add custom parsers on top of that, but they'd still be helpful to narrow down the analysis, right?

**Comment by peti2001** [comment]
That is correct and PHP might a special case. Here I explained why we decided not to use dependency managers: https://github.com/codersrank-org/libraries/issues/45#issuecomment-652000527
