### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by d3xt3r2909** [codersrank-org/repo_info_extractor#64]
I got this error after analyzing command. (Windows 10 OS)

`[20/11/2019 17:55:06] Copying the repository to a temporary location, this can take a while...
Traceback (most recent call last):
  File "src\main.py", line 46, in <module>
    main()
  File "src\main.py", line 37, in main
    initialize(args.directory, args.skip_obfuscation, args.output, args.parse_libraries, args.email, args.skip_upload)
  File "C:\Users\nihad\AndroidStudioProjects\repo_info_extractor\src\init.py", line 70, in initialize
    libs = al.get_libraries()
  File "C:\Users\nihad\AndroidStudioProjects\repo_info_extractor\src\analyze_libraries.py", line 33, in get_libraries
    shutil.copytree(self.basedir, tmp_repo_path, symlinks=True)
  File "C:\ProgramData\Anaconda3\lib\shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('C:\\Users\\nihad\\AndroidStudioProjects\\REPO_NAME\\android\\vendor\\bundle\\ruby\\2.3.0\\gems\\fastlane-2.123.0\\fastlane\\swift\\FastlaneSwiftRunner\\FastlaneSwiftRunner.xcodeproj\\project.xcworkspace\\xcuserdata\\josh.xcuserdatad\\UserInterfaceState.xcuserstate', 'C:\\Users\\nihad\\AppData\\Local\\Temp\\38febda8-c011-4c53-8eae-a549cc2c2f87\\android\\vendor\\bundle\\ruby\\2.3.0\\gems\\fastlane-2.123.0\\fastlane\\swift\\FastlaneSwiftRunner\\FastlaneSwiftRunner.xcodeproj\\project.xcworkspace\\xcuserdata\\josh.xcuserdatad\\UserInterfaceState.xcuserstate', "[Errno 2] No such file or directory: 'C:\\\\Users\\\\nihad\\\\AppData\\\\Local\\\\Temp\\\\38febda8-c011-4c53-8eae-a549cc2c2f87\\\\android\\\\vendor\\\\bundle\\\\ruby\\\\2.3.0\\\\gems\\\\fastlane-2.123.0\\\\fastlane\\\\swift\\\\FastlaneSwiftRunner\\\\FastlaneSwiftRunner.xcodeproj\\\\project.xcworkspace\\\\xcuserdata\\\\josh.xcuserdatad\\\\UserInterfaceState.xcuserstate'")]`

**Comment by peti2001** [comment]
Hi,

We could reproduce it and we are fixing it. On the meanwhile, you can use the `run-docker.bat`, for use it worked.

**Comment by rabxly** [comment]
The issue was fixed in #70
