### ISSUE TITLE
SyntaxError: invalid syntax on mac

### ISSUE THREAD

**Issue by shaikhriyaz434** [codersrank-org/repo_info_extractor#87]
got the error while trying to execute run.sh on mac
![Screenshot 2020-02-23 at 2 07 30 PM](https://user-images.githubusercontent.com/16817782/75106787-10eeb400-5646-11ea-8d3b-5512093628cc.png)

**Comment by peti2001** [comment]
We released a new version of the `repo_info_extractor`. This is not relevant anymore.
